USE [master]
GO

/****** Object:  Database [BookishDB]    Script Date: 13/04/2018 14:02:20 ******/
CREATE DATABASE [BookishDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookishDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BookishDB.mdf' , SIZE = 512000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BookishDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BookishDB_log.ldf' , SIZE = 102400KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [BookishDB] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookishDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BookishDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BookishDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BookishDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BookishDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BookishDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [BookishDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BookishDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BookishDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BookishDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BookishDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BookishDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BookishDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BookishDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BookishDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BookishDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BookishDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BookishDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BookishDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BookishDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BookishDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BookishDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BookishDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BookishDB] SET RECOVERY FULL 
GO

ALTER DATABASE [BookishDB] SET  MULTI_USER 
GO

ALTER DATABASE [BookishDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BookishDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BookishDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BookishDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BookishDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BookishDB] SET QUERY_STORE = OFF
GO

USE [BookishDB]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [BookishDB] SET  READ_WRITE 
GO


